### ISSUE TITLE
broken things and suggestion

### ISSUE THREAD

**Issue by anthonyhuang07** [Hello56721/chess#1]
## ISSUES
- clicking a piece and dropping it ends the turn
- not for pawns and knights; but for every other piece
- when king goes into check, game crashes
## SUGGESTION:
have an option to enable board rotation and disable it on default

**Comment by earthtraveller1** [comment]
> - clicking a piece and dropping it ends the turn
> - not for pawns and knights; but for every other piece

Fixed in the most recent commit.

> - when king goes into check, game crashes

Unfortunately, I was unable to replicate this error. But what does happen is going into check is somehow legal so...

> - have an option to enable board rotation and disable it on default

Working on it right now.

**Comment by anthonyhuang07** [comment]
I tried it again, it seems that it's not the king that goes into check that crashes the game, it's the move after you kill the king that causes it to crash. Please make a "You Won" screen for when you kill the king, because you're still allowed to do 1 more move before the game crashes

**Comment by earthtraveller1** [comment]
Oh, okay.
